name: npm i test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    jobs:
      build: npm i test
    
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            node-version: [12.x]
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install dependencies
          run: npm install
          
jobs:
  build: npm build test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build