name: npm i test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
            name: Check out repository
          - uses: actions/setup-node@v1
            name: Set up Node.js
            with:
              node-version: [12.x]
          - run: |
              npm i
              npm ci
              npm run build
              npm test
            name: Build and Test